tunnel: __CLOUDFLARE_TUNNEL_ID__
credentials-file: /Users/__USER__/.cloudflared/__CLOUDFLARE_TUNNEL_ID__.json

ingress:
  - hostname: __HA_DOMAIN__
    service: http://127.0.0.1:8123
  - service: http_status:404
